### ISSUE TITLE
Creating sites in 1.10 doesn't create db or htdocs

### ISSUE THREAD

**Issue by bradp** [bradp/vv#268]
@jtsternberg ran into some issues.

Should run 1.10 through another round of testing and try to figure out what caused this.

**Comment by Mte90** [comment]
i confirm the bug, i tried running the vvv-init.sh from vagrant the installation works but there is no way to access the website

**Comment by nandotess** [comment]
Probably the same bug I related right now - #269. Sorry, I didn't see this bug before, only #243 (that is closed).

**Comment by bradp** [comment]
Just pushed up 1.10.1, which should now fix this issue.

**Comment by voltronik** [comment]
For some reasons, vv --update does't want to update to the latest version. It always says: 

>Your version of vv ( 1.10.0 )  does not match the current Github version ( 1.10.1 ). Please update with vv --update

This happens even after completely removing `vv` and installing again using brew from scratch.

**Comment by bradp** [comment]
That happens. see [updating](https://github.com/bradp/vv#updating) for how to fix.

**Comment by bradp** [comment]
Specifically, 

> First, and simplest, run vv --force-update. Second, if that does not work you can safely uninstall Variable VV and re-install it via homebrew, you can do this with these commands: brew remove vv then brew untap bradp/vv and finally, run the install command brew install bradp/vv/vvas mentioned above. You will not lose any settings or sites.

**Comment by voltronik** [comment]
Thanks but I've done all of that. Several times. I even manually delete Homebrew's cache so that it downloaded a new version of vv from GitHub but still getting the same error.

**Comment by bradp** [comment]
`vv --force-update` completely bypasses Homebrew, so please try that again.

**Comment by voltronik** [comment]
Tried that. Here's my output: 

> Jacks-MBA:~ Jack$ vv --force-update
> Your version of vv ( 1.10.0 )  does not match the current Github version ( 1.10.1 ). Please update with vv --update 
> Forcing boostrapped update... 
> /usr/local/bin/vv: line 331: /usr/local/bin/vv: Permission denied
> [Success] vv has been updated to the latest version. Thanks! 
> Jacks-MBA:~ Jack$ sudo vv --force-update
> Password:
> Your version of vv ( 1.10.0 )  does not match the current Github version ( 1.10.1 ). Please update with vv --update 
> Forcing boostrapped update... 
> [Success] vv has been updated to the latest version. Thanks! 
> Jacks-MBA:~ Jack$ vv --version
> Your version of vv ( 1.10.0 )  does not match the current Github version ( 1.10.1 ). Please update with vv --update 
> vv version 1.10.0

**Comment by bradp** [comment]
facepalm, didn't update the ver number correctly. Pushing a new update now.

**Comment by nanomoffet** [comment]
I'm still experiencing this issue. I successfully force updated to 1.10.2, ran vagrant provision, deleted all my installs and created new ones, but still no htdocs or database or access to the site.

**Comment by BrevAlessio** [comment]
@nanomoffet same situation, how did you solved it?

**Comment by mnelson4** [comment]
I updated using `vv update` andn got this, then tried updating via git and got the same problem again
